### ISSUE TITLE
海外VPS服务器部署显示“不可用”的问题的解决方案

### ISSUE THREAD

**Issue by xzy103** [adams549659584/go-proxy-bingai#256]
# 01 问题场景
我买了一台海外的VPS服务器，按照项目主页介绍中docker配置的方式启动项目，并且使用nginx做了端口转发。
部署好后，页面虽然可以访问，但我自己的域名那里提示“不可用”。
- （图1）按照主页的docker配置
<img width="649" alt="image" src="https://github.com/adams549659584/go-proxy-bingai/assets/40889019/48e35a1b-aa4b-467c-914c-261c358ecee6">

- （图2）提示不可用
<img width="662" alt="屏幕截图 2023-06-19 001330" src="https://github.com/adams549659584/go-proxy-bingai/assets/40889019/d0ec1e59-4632-4a40-a459-f95ec3652450">

# 02 参考大佬的分享
有幸看到大佬 @showlee的分享 #154 
但是大佬的解决方案与我部署的方案不同。
大佬使用docker部署时，拉取的镜像是chishin/nginx-proxy-manager-zh，这是一个集合了nginx和proxy的镜像。
而我拉取的是adams549659584/go-proxy-bingai（这与项目作者提供的docker-compose.yml是一致的），我的nginx是自己单独配置的。
在这个issue的讨论中，有小伙伴提到`打开websocks支持`可以解决问题。
<img width="524" alt="image" src="https://github.com/adams549659584/go-proxy-bingai/assets/40889019/6bbcbd0e-cee8-4c77-9cb2-542406cd73ea">
**顺着这个思路，我更改了自己的nginx.conf，解决了问题。**

# 03 我的配置
## 3.1 项目本体docker
使用项目作者在README.md中提供的配置。（根据自己情况略作了更改）
```yml
version: '3.3'
services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai  
    # 自启动
    # restart: unless-stopped
    ports:
      - 1003:8080
```
## 3.2 nginx的配置
我在nginx的请求转发配置中，增加了3行（其他没变），顺利解决了问题。
**这3行的作用是让nginx支持WebSocket的请求转发。**
```
...
http {
    ...
    server {
        ...
        location / {
            # 原配置中只有这1行
            proxy_pass http://127.0.0.1:1003;
            # 新配置增加了下面3行
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        ...
    }
}
```
# 04 解决后的图
<img width="669" alt="屏幕截图 2023-06-19 003512" src="https://github.com/adams549659584/go-proxy-bingai/assets/40889019/466837b7-585e-4799-bccf-297170694bc2">

可以愉快的使用了！
