### ISSUE TITLE
help：无法更改端口

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#30]
你好，我的vps由于8080端口被占用，想用其他端口，然后把docker compose修改为如下两种都不行：

~~~
version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai
    # 自启动
    restart: unless-stopped
    ports:
      - 8383:8383
    # environment:
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx 

~~~

另外一种：
~~~
version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai
    # 自启动
    restart: unless-stopped
    ports:
      - 8383:8080
    # environment:
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx 
~~~

docker的输出日志都是：

~~~
2023/05/19 08:22:52 Starting BingAI Proxy At :8080
~~~

**Comment by adams549659584** [comment]
docker 网络模式不是 host 的话， 容器中的端口不占用 vps的，就第二种就可以了的，访问的端口就是 8383，映射了容器中的8080，确实想改容器中服务端口的话，也可以在下面环境变量那里设置 PORT=8383

```yaml
version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai  
    # 自启动
    restart: unless-stopped
    ports:
      - 8383:8383
    environment:
      - PORT=8383
```

**Comment by justincnn** [comment]
> docker 网络模式不是 host 的话， 容器中的端口不占用 vps的，就第二种就可以了的，访问的端口就是 8383，映射了容器中的8080，确实想改容器中服务端口的话，也可以在下面环境变量那里设置 PORT=8383
> 
> ```yaml
> version: '3'
> 
> services:
>   go-proxy-bingai:
>     # 镜像名称
>     image: adams549659584/go-proxy-bingai
>     # 容器名称
>     container_name: go-proxy-bingai  
>     # 自启动
>     restart: unless-stopped
>     ports:
>       - 8383:8383
>     environment:
>       - PORT=8383
> ```

我本来想用host模式，但是把compose代码改为如下，提示出错：

~~~
version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    network_mode: "host"
    # 容器名称
    container_name: go-proxy-bingai
    # 自启动
    restart: unless-stopped
    ports:
      - 8383:8383
    # environment:
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx 
~~~

**Comment by adams549659584** [comment]
host 模式不需要端口映射了的，会占用端口，直接配置环境变量就好

```yaml
version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    network_mode: host
    # 容器名称
    container_name: go-proxy-bingai
    # 自启动
    restart: unless-stopped
    environment:
      - PORT=8383
      # - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
      # - Go_Proxy_BingAI_SOCKS_USER=xxx
      # - Go_Proxy_BingAI_SOCKS_PWD=xxx 
```
