### ISSUE TITLE
2023.7.31海外服务器，利用Docker部署、宝塔面板反代小白教程

### ISSUE THREAD

**Issue by skyfly2000** [adams549659584/go-proxy-bingai#388]
#最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai
#确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云和Google云VPS都已经被封禁，Cloudflare的聊天服务器也被ban
#vps安装宝塔面板
#根据提示宝塔内安装相关插件和Nginx
#宝塔安装Docker
#宝塔 网站 添加站点 添加解析好的域名
#宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https 
#宝塔 网站 反向代理(vps地址:http://xxx:8080/)
#ssh连接vps
#下载1.95版二进制文件（ARM 自行替换最新相对应文件地址）
wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz
#解压二进制文件
tar -xzvf go-proxy-bingai-linux-amd64.tar.gz
#挂载二进制文件
docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
#赋予go-proxy-bingai文件夹555权限
chmod +x go-proxy-bingai
OK，部署完毕
升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可

**Comment by gxon2019** [comment]
受不了，没用多久又失效，我算是清醒过来了，不搞了，有时间搞这个，不如直接搞代理。

**Comment by Harry-zklcdc** [comment]
> 受不了，没用多久又失效，我算是清醒过来了，不搞了，有时间搞这个，不如直接搞代理。

共享Cookie的问题吧，我这边自己一个人的Cookie可以用一个礼拜左右，然后过期需要重新登录

**Comment by skyfly2000** [comment]
> 受不了，没用多久又失效，我算是清醒过来了，不搞了，有时间搞这个，不如直接搞代理。

微软在天天折腾，不断的升级验证……，开源本身就是要折腾至死……，看目前情况，和谐上网也是在逐步封禁，ChatGPT已经封了很多家vps了，和谐上网估计很快也用不成。so找家好的VPS，私有化部署才是王道

**Comment by yihaoshiyan** [comment]
这个网站好像还能用https://www.agbgpt.com/

**Comment by skyfly2000** [comment]
> 这个网站好像还能用https://www.agbgpt.com/

某自媒体冒充AI大拿，盗用项目给自己赚钱的，把开源地址和原作者信息去掉了，违反开源协议，无耻至极

**Comment by 7noemo** [comment]
最新不是v1.10.1吗

**Comment by yihaoshiyan** [comment]
> #最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai #确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban #vps安装宝塔面板 #根据提示宝塔内安装相关插件和Nginx #宝塔安装Docker #宝塔 网站 添加站点 添加解析好的域名 #宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https #宝塔 网站 反向代理(vps地址:http://xxx:8080/) #ssh连接vps #下载1.95版二进制文件（ARM 自行替换最新相对应文件地址） wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #挂载二进制文件 docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai #赋予go-proxy-bingai文件夹555权限 chmod +x go-proxy-bingai OK，部署完毕 升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可

大佬为啥我不按照步骤走完后还是不能用啊
![image](https://github.com/adams549659584/go-proxy-bingai/assets/97588063/7a7452cb-88f3-4730-a862-ecfe0c8802d3)

**Comment by skyfly2000** [comment]
> > #最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai #确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban #vps安装宝塔面板 #根据提示宝塔内安装相关插件和Nginx #宝塔安装Docker #宝塔 网站 添加站点 添加解析好的域名 #宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https #宝塔 网站 反向代理(vps地址:http://xxx:8080/) #ssh连接vps #下载1.95版二进制文件（ARM 自行替换最新相对应文件地址） wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #挂载二进制文件 docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai #赋予go-proxy-bingai文件夹555权限 chmod +x go-proxy-bingai OK，部署完毕 升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可
> 
> 大佬为啥我不按照步骤走完后还是不能用啊 ![image](https://user-images.githubusercontent.com/97588063/257181792-7a7452cb-88f3-4730-a862-ecfe0c8802d3.png)

确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban

**Comment by skyfly2000** [comment]
> 最新不是v1.10.1吗

中午刚更新的

**Comment by yihaoshiyan** [comment]
> > > #最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai #确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban #vps安装宝塔面板 #根据提示宝塔内安装相关插件和Nginx #宝塔安装Docker #宝塔 网站 添加站点 添加解析好的域名 #宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https #宝塔 网站 反向代理(vps地址:http://xxx:8080/) #ssh连接vps #下载1.95版二进制文件（ARM 自行替换最新相对应文件地址） wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #挂载二进制文件 docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai #赋予go-proxy-bingai文件夹555权限 chmod +x go-proxy-bingai OK，部署完毕 升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可
> > 
> > 
> > 大佬为啥我不按照步骤走完后还是不能用啊 ![image](https://user-images.githubusercontent.com/97588063/257181792-7a7452cb-88f3-4730-a862-ecfe0c8802d3.png)
> 
> 确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban

用的时优刻得的服务器https://console.ucloud.cn/

**Comment by yihaoshiyan** [comment]
> > 最新不是v1.10.1吗
> 
> 中午刚更新的

大佬，能参考一下你的反代理嘛？

**Comment by skyfly2000** [comment]
> > > > #最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai #确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban #vps安装宝塔面板 #根据提示宝塔内安装相关插件和Nginx #宝塔安装Docker #宝塔 网站 添加站点 添加解析好的域名 #宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https #宝塔 网站 反向代理(vps地址:http://xxx:8080/) #ssh连接vps #下载1.95版二进制文件（ARM 自行替换最新相对应文件地址） wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #挂载二进制文件 docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai #赋予go-proxy-bingai文件夹555权限 chmod +x go-proxy-bingai OK，部署完毕 升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可
> > > 
> > > 
> > > 大佬为啥我不按照步骤走完后还是不能用啊 ![image](https://user-images.githubusercontent.com/97588063/257181792-7a7452cb-88f3-4730-a862-ecfe0c8802d3.png)
> > 
> > 
> > 确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban
> 
> 用的时优刻得的服务器https://console.ucloud.cn/

你玩呢？不看标题么？海外服务器，海外~~~

**Comment by skyfly2000** [comment]
> > > 最新不是v1.10.1吗
> > 
> > 
> > 中午刚更新的
> 
> 大佬，能参考一下你的反代理嘛？

说的很清楚了，目标URL输入：vps地址：http://XXX:8080，其他不用动

**Comment by yihaoshiyan** [comment]
> 目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁

是美国的啊，不是这样吗？(・∀・(・∀・(・∀・*)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/97588063/f5a7895d-0c2d-471a-ad97-48ee0a320d1a)

**Comment by yihaoshiyan** [comment]
> > > > 最新不是v1.10.1吗
> > > 
> > > 
> > > 中午刚更新的
> > 
> > 
> > 大佬，能参考一下你的反代理嘛？
> 
> 说的很清楚了，目标URL输入：vps地址：[http://XXX:8080，其他不用动](http://XXX:8080%EF%BC%8C%E5%85%B6%E4%BB%96%E4%B8%8D%E7%94%A8%E5%8A%A8)

是美国的啊，难道不是这样吗？(・∀・(・∀・(・∀・*)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/97588063/9a6c613a-7fbd-4dbf-bbe2-dbe46bd4af4d)

**Comment by skyfly2000** [comment]
> > > > > 最新不是v1.10.1吗
> > > > 
> > > > 
> > > > 中午刚更新的
> > > 
> > > 
> > > 大佬，能参考一下你的反代理嘛？
> > 
> > 
> > 说的很清楚了，目标URL输入：vps地址：[http://XXX:8080，其他不用动](http://XXX:8080%EF%BC%8C%E5%85%B6%E4%BB%96%E4%B8%8D%E7%94%A8%E5%8A%A8)
> 
> 是美国的啊，难道不是这样吗？(・∀・(・∀・(・∀・*) ![image](https://user-images.githubusercontent.com/97588063/257187699-9a6c613a-7fbd-4dbf-bbe2-dbe46bd4af4d.png)

被ban了呗，仔细看说明

**Comment by yihaoshiyan** [comment]
> > > > > > 最新不是v1.10.1吗
> > > > > 
> > > > > 
> > > > > 中午刚更新的
> > > > 
> > > > 
> > > > 大佬，能参考一下你的反代理嘛？
> > > 
> > > 
> > > 说的很清楚了，目标URL输入：vps地址：[http://XXX:8080，其他不用动](http://XXX:8080%EF%BC%8C%E5%85%B6%E4%BB%96%E4%B8%8D%E7%94%A8%E5%8A%A8)
> > 
> > 
> > 是美国的啊，难道不是这样吗？(・∀・(・∀・(・∀・*) ![image](https://user-images.githubusercontent.com/97588063/257187699-9a6c613a-7fbd-4dbf-bbe2-dbe46bd4af4d.png)
> 
> 被ban了呗，仔细看说明

好的感谢大佬，他好像又抽风，抽回来了
![image](https://github.com/adams549659584/go-proxy-bingai/assets/97588063/5007487c-3ce3-4bee-93e5-7feee0569e5b)

**Comment by Harry-zklcdc** [comment]
> 这个网站好像还能用https://www.agbgpt.com/

建议删除并举报，开源社区不欢迎不尊重开源成果的人

**Comment by Harry-zklcdc** [comment]
> 说的很清楚了，目标URL输入：vps地址：[http://XXX:8080，其他不用动](http://XXX:8080%EF%BC%8C%E5%85%B6%E4%BB%96%E4%B8%8D%E7%94%A8%E5%8A%A8)

其实 `http://127.0.0.1:8080` 就行了

**Comment by Harry-zklcdc** [comment]
我怀疑这个是没有开websocket

**Comment by SokWith** [comment]
cf、vercel、replit测试可用性： 23-7-31 可用：

1、cf下的NewBingGoGo，内置账号： https://web.nbing.eu.org
2、vercel下的go-proxy，内置账号：   https://vercel.nbing.eu.org
3、replit下的go-proxy，无账号：        https://replit.nbing.eu.org

![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/61876c2f-d79b-4ba1-90db-110cb7fda250)、


用的其实都是cf的workes代理，觉得是因为cf的workes可能频繁跳ip，所以很容易就被微软锁账号要求真人验证。

8月1日情况：
1、web站点被爬虫大量访问造成转发的ip锁了，更换ip后发现内置的用户ID正常；重新将站点命名为cfweb，看能否避免爬虫。
2、vercel坚持了一整天，被一个讲俄语的朋友频繁使用，最后突然倒下；重新科学登录账户ID后恢复使用。
3、replit很快就倒下了，不是ID锁，是ip锁了，并且再也不能创建新的主题。但可以打开ID原来的聊天记录继续聊下去。跟踪发现是 turing/conversation/create GET失败。

**Comment by Nothingness-Void** [comment]
那我来分享一下docker-compose带Caddy反代的配置文件吧，适合小白一键部署
```
version: "3" 
services:
  go-proxy-bingai:
    container_name: go-proxy-bingai
    image: nothingnessvoid/go-proxy-bingai:latest
    ports:
      - 8088:8088         # 容器端口映射到宿主机8088端口；宿主机监听端口可按需改为其它端口
    networks:
          - caddy
    restart: unless-stopped
    environment:
      - PORT=8088
    # KievRPSSecAuth Cookie的值
      - USER_KievRPSSecAuth=123456_qwerty
    # 默认用户 Cookie 设置，可选，不推荐使用，固定前缀 Go_Proxy_BingAI_USER_TOKEN 可设置多个，未登录用户将随机使用，多人共用将很快触发图形验证，并很快达到该账号的24小时限制
      - Go_Proxy_BingAI_USER_TOKEN_1=123456_qwerty
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_1=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_2=xxx
    labels:
      caddy: xxx.域名.com # 填写你预先解析到服务器 ip 上的域名
      caddy.reverse_proxy: "{{upstreams 8088}}"
      
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 公开 Docker 的套接字文件
      - caddy_data:/data # 存储 Caddy 的持久数据
    environment:
      - CADDY_INGRESS_NETWORKS=caddy # 告诉 Caddy 它可以代理 Docker 网络中的服务
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

```

注意 运行前需要先输入
`docker network create caddy`
来创建一个网络
![image](https://github.com/adams549659584/go-proxy-bingai/assets/55913486/992d2d5a-f505-4c5f-9b39-0f7866d8fc42)
显示这样之后直接访问你在配置文件里填写的xxx.域名.com就可以访问了
